// Comprehensive keyword monitoring list for Elche (Elx) police OSINT operations.
// Organized by category for reuse across Twitter, Facebook, Instagram, and other platforms.
// Languages covered: Spanish (Castellano), Valencian/Catalan (Valencià), English.

export interface SearchQueryConfig {
  query: string;
  maxPages: number;
  label: string;
}

export const KEYWORDS = {
  semana_santa: [
    "Domingo de Ramos Elche",
    "Lunes Santo Elche",
    "Martes Santo Elche",
    "Miércoles Santo Elche",
    "Jueves Santo Elche",
    "Viernes Santo Elche",
    "Sábado Santo Elche",
    "Domingo de Resurrección Elche",
    "Semana Santa Elche",
    "procesión del Silencio",
    "procesión del Encuentro",
    "procesión del Santo Entierro",
    "salida procesional Elche",
    "levantá Elche",
    "paso procesión Elche",
    "trono procesión Elche",
    "nazarenos Elche",
    "cofrades Elche",
    "procesiones Elche",
    "Holy Week Elche",
    "Elche Easter",
    "Setmana Santa Elx",
    "tamborrada Elche",
    "saeta Elche",
  ],

  cofradias: [
    "cofradías Elche",
    "hermandad Elche",
    "cofradía del Silencio Elche",
    "cofradía del Santo Entierro Elche",
    "cortejo fúnebre Elche",
    "penitentes Elche",
    "capirotes Elche",
    "costaleros Elche",
    "capataz procesión Elche",
    "paso de misterio Elche",
  ],

  locations_centro: [
    "Plaça de Baix",
    "Plaza del Congreso Eucarístico",
    "Calle Corredora",
    "Corredora Elche",
    "Puente de la Virgen",
    "Paseo de la Estación",
    "Plaza de Santa Isabel",
    "Calahorra Elche",
    "Portal de Elche",
    "Plaça de les Flors",
    "Plaza Blanca",
    "Glorieta Elche",
    "Calle Major de la Vila",
    "Palacio de Altamira",
    "Puente de Altamira",
  ],

  locations_transit: [
    "Calle Reina Victoria Elche",
    "Calle Jorge Juan Elche",
    "Calle Hospital Elche",
    "RENFE Elche",
    "Estación de Autobuses Elche",
    "Estación Elche Parque",
    "río Vinalopó",
    "entorno Vinalopó Elche",
    "Basílica de Santa María Elche",
    "Basílica Santa María",
  ],

  locations_zones: [
    "Carrús Elche",
    "Altabix Elche",
    "El Raval Elche",
    "Sector V Elche",
    "Nou Altabix Elche",
    "Ciudad Deportiva Elche",
    "Parque Municipal Elche",
    "Huerto del Cura",
    "Mercado Central Elche",
    "Plaza de España Elche",
    "El Pantano Elche",
    "Playa El Altet",
    "Arenales del Sol",
    "La Marina Elche",
  ],

  violence: [
    "pelea Elche",
    "riña Elche",
    "altercado Elche",
    "agresión Elche",
    "disturbio Elche",
    "desorden Elche",
    "alboroto Elche",
    "violencia Elche",
    "enfrentamiento Elche",
    "ataque Elche",
    "bronca Elche",
    "follón Elche",
    "movida Elche",
    "jaleo Elche",
    "puñetazo Elche",
    "navaja Elche",
    "apuñalamiento Elche",
    "paliza Elche",
    "agresión sexual Elche",
    "violencia machista Elche",
    "violencia de género Elche",
    "amenaza Elche",
    "intimidación Elche",
    "acoso Elche",
  ],

  crowd: [
    "aglomeración Elche",
    "avalancha Elche",
    "empujones Elche",
    "hacinamiento Elche",
    "intransitable Elche",
    "muchedumbre Elche",
    "desbordamiento Elche",
    "pánico Elche",
    "estampida Elche",
    "colapso gente Elche",
    "lleno a reventar Elche",
    "petado Elche",
    "no se puede pasar Elche",
    "masificación Elche",
    "evacuación masiva Elche",
  ],

  alcohol: [
    "macrobotellón Elche",
    "litrona Elche",
    "botellón Elche",
    "borrachos Elche",
    "fiesta improvisada Elche",
    "quedada botellón Elche",
    "embriaguez Elche",
    "intoxicación etílica Elche",
    "previa Elche",
    "gente borracha Elche",
    "fiesta espontánea Elche",
    "pre-fiesta Elche",
    "after Elche",
    "beber calle Elche",
    "cubatas calle Elche",
  ],

  drugs: [
    "drogas Elche",
    "trapicheo Elche",
    "narcotráfico Elche",
    "camello Elche",
    "punto venta droga Elche",
    "cocaína Elche",
    "marihuana Elche",
    "pastillas Elche",
    "sobredosis Elche",
    "jeringuilla Elche",
    "plantación marihuana Elche",
    "alijo Elche",
  ],

  theft: [
    "carterista Elche",
    "robo móvil Elche",
    "hurto bolso Elche",
    "tirón Elche",
    "robos Elche",
    "carterista procesión",
    "robo Elche",
    "ladrón Elche",
    "sustracción Elche",
    "vandalismo Elche",
    "atraco Elche",
    "robo con fuerza Elche",
    "robo coche Elche",
    "ocupación ilegal Elche",
    "okupa Elche",
  ],

  medical: [
    "herido Elche",
    "ambulancia Elche",
    "ambulancia procesión",
    "evacuación Elche",
    "desmayo Elche",
    "golpe de calor Elche",
    "atropello Elche",
    "accidente Elche",
    "urgencia Elche",
    "persona inconsciente Elche",
    "parada cardíaca Elche",
    "atención sanitaria Elche",
  ],

  structural: [
    "caída estructura Elche",
    "caída trono Elche",
    "caída paso Elche",
    "derrumbe Elche",
    "desprendimiento Elche",
    "peligro estructural Elche",
    "socavón Elche",
    "hundimiento Elche",
  ],

  unauthorized: [
    "fiesta ilegal Elche",
    "rave Elche",
    "convocatoria nocturna Elche",
    "quedada no autorizada Elche",
    "concentración no autorizada Elche",
    "fiesta clandestina Elche",
    "sound system Elche",
    "macroquedada Elche",
    "festival ilegal Elche",
    "acampada ilegal Elche",
    "hoguera ilegal Elche",
    "fiesta privada Elche",
  ],

  terrorism: [
    "atentado Elche",
    "amenaza bomba Elche",
    "terrorismo Elche",
    "radicalismo Elche",
    "yihadismo Elche",
    "explosivo Elche",
    "paquete sospechoso Elche",
    "mochila abandonada Elche",
    "alerta terrorista Elche",
    "extremismo Elche",
    "radicalización Elche",
    "amenaza Basílica",
    "incitación odio Elche",
  ],

  fraud: [
    "estafa Elche",
    "entradas falsas Elche",
    "tickets falsos Elche",
    "fraude Elche",
    "timo Elche",
    "venta ilegal entradas Elche",
    "reventa entradas Elche",
    "comprar entradas procesiones",
    "venta ambulante ilegal Elche",
    "falsificación Elche",
  ],

  perception: [
    "seguridad Elche",
    "policía Elche",
    "queja policía Elche",
    "inseguro Elche",
    "miedo Elche",
    "queja Semana Santa",
    "denuncia ciudadana Elche",
    "protesta Elche",
    "manifestación Elche",
    "corte tráfico Elche",
    "queja vecinal Elche",
    "Policía Local Elche",
  ],

  valencian: [
    "Setmana Santa Elx",
    "processó Elx",
    "seguretat Elx",
    "festes Elx",
    "baralla Elx",
    "robatori Elx",
    "perill Elx",
    "emergència Elx",
    "incendi Elx",
    "destrosses Elx",
  ],
} as const;

export type KeywordCategory = keyof typeof KEYWORDS;

export const ALL_KEYWORDS: string[] = Object.values(KEYWORDS).flat();

// Pre-built search queries optimized for Twitter API.
// Each query uses "Elche" as a dork combined with category-specific terms.
export const TWITTER_SEARCH_QUERIES: SearchQueryConfig[] = [
  { query: '"Elche"', maxPages: 5, label: "general" },
  { query: '"Semana Santa" "Elche"', maxPages: 2, label: "semana_santa" },
  { query: '"procesión" "Elche"', maxPages: 2, label: "processions" },
  { query: 'pelea "Elche"', maxPages: 2, label: "violence_pelea" },
  { query: 'altercado "Elche"', maxPages: 2, label: "violence_altercado" },
  { query: 'botellón "Elche"', maxPages: 2, label: "alcohol_botellon" },
  { query: 'macrobotellón "Elche"', maxPages: 2, label: "alcohol_macro" },
  { query: 'robo "Elche"', maxPages: 2, label: "theft" },
  { query: 'accidente "Elche"', maxPages: 2, label: "medical" },
  { query: 'policía "Elche"', maxPages: 2, label: "police" },
  { query: 'droga "Elche"', maxPages: 2, label: "drugs" },
  { query: 'estafa "Elche"', maxPages: 2, label: "fraud" },
  { query: 'vandalismo "Elche"', maxPages: 2, label: "vandalism" },
  { query: '"Plaça de Baix"', maxPages: 2, label: "location_placa_baix" },
  { query: '"Calle Corredora"', maxPages: 2, label: "location_corredora" },
  { query: 'rave "Elche"', maxPages: 2, label: "unauthorized" },
  { query: 'atentado "Elche"', maxPages: 2, label: "terrorism" },
  { query: 'inseguro "Elche"', maxPages: 2, label: "insecurity" },
  { query: 'manifestación "Elche"', maxPages: 2, label: "protest" },
  { query: '"Basílica Santa María"', maxPages: 2, label: "location_basilica" },
];
